### ISSUE TITLE
List of commands(methods) in plugin

### ISSUE THREAD

**Issue by GospodinNoob** [mixer/interactive-unreal-plugin#1]
Hi.
Is somewere exists full list of methods, which can be used for communicating with chat and channel? Read, and write messages from c ++ for example. I could not find smth like this in tutorial. If smth like this exists, can you give a link, please. May be i missed page with this information)

Thanks

**Comment by payzer** [comment]
There aren't APIs for communicating with chat and the channel. Thank you for the feedback though. We will take the suggestion into our planning process.

**Comment by AechDub** [comment]
Chat integration added with [PR #13](https://github.com/mixer/interactive-unreal-plugin/pull/13)
