### ISSUE TITLE
incompatibility with 4.15.3, 4.17.1

### ISSUE THREAD

**Issue by GospodinNoob** [mixer/interactive-unreal-plugin#2]
Plugin incompatible with this versions of Unreal engine (include last 4.17.1). I tried to active him in "clean" project.
![default](https://user-images.githubusercontent.com/12844692/29977999-14db2d7c-8f48-11e7-81bf-e2817ddfa5f7.jpeg)
After this, project can not be runned any more. "Try to rebuilding from source manualy" error.

**Comment by GospodinNoob** [comment]
Same error in 4.16.3

**Comment by AechDub** [comment]
The latest build should work with 4.17 and 4.18.  Let us know if you're still having problems.
