### ISSUE TITLE
Build with the default interactive-cpp V2 doesn't run on Windows 7 for us.

### ISSUE THREAD

**Issue by LuaChunk** [mixer/interactive-unreal-plugin#46]
Hi,

We've recently upgraded our game to Unreal 4.20 and the latest version of interactive-unreal-plugin. Things were mostly working fine, but our developer that runs Windows 7 can no longer run the game because the mixer module fails to load. It seems to require a version of WinHttp.dll that Windows 7 doesn't have.

Regards,
Ryan.

**Comment by FacePalm-exe** [comment]
The specific function it's attempting to use is the following:
[https://docs.microsoft.com/en-us/windows/desktop/api/winhttp/nf-winhttp-winhttpwebsocketcompleteupgrade](https://docs.microsoft.com/en-us/windows/desktop/api/winhttp/nf-winhttp-winhttpwebsocketcompleteupgrade)

As mentioned in the article:

> Requirements:
> Windows version Windows 8 [desktop apps only] Windows Server 2012 [desktop apps only]
