### ISSUE TITLE
Compiling with backend interactive-cpp V1 has lots of warnings in UE4 4.20

### ISSUE THREAD

**Issue by LuaChunk** [mixer/interactive-unreal-plugin#47]
Hi,

We've recently upgraded our game to Unreal 4.20 and the latest version of interactive-unreal-plugin. We're sticking with interactive-cpp V1 for now. When building a Development Win64 configuration I'm getting a lot of compiler warnings with 4.20 and VS2017 that I wasn't seeing on 4.19 with VS 2015.
```
warning C4652: compiler option 'C++ Exception Handling Unwinding' inconsistent with precompiled header; current command-line option will override that defined in the precompiled header
warning C4651: '/D_HAS_EXCEPTIONS=0' specified for precompiled header but not for current compile
```
For now we can't upgrade to interactive-cpp V2 because it doesn't run on Windows 7. I tried disabling exception handling but it just caused a heap of errors in the libraries included in the mixer code.

Is anyone else seeing this?

Regards,
Ryan.

**Comment by gostay** [comment]
Our understanding is that the unreal plugin is not prioritized by the mixer team currently, so I don't think you should wait for a solution from them.  Is there anything else you can do, like go back to 4.19, or use VS 2015 to build the plugin for 4.20?

We're on 4.19, and I've been hesitant to upgrade.  We're using interactive v2.

Sorry if none of this is useful - I'm at least trying to provide solidarity.

**Comment by botman99** [comment]
I was seeing the same warnings with vs2015 on UE 4.20.  I modified MixerInteractivity.build.cs as follows:

remove the line "PCHUsage = PCHUsageMode.UseExplicitOrSharedPCHs;" and replace it with this:

PCHUsage = ModuleRules.PCHUsageMode.NoSharedPCHs;
PrivatePCHHeaderFile = "Public/MixerInteractivityModule.h";
