### ISSUE TITLE
Build Fail with MICROSOFT-XBOX-ATG /release_uwp 

### ISSUE THREAD

**Issue by JustinBWatson** [mixer/interactive-unreal-plugin#6]
Unreal Engine Editor Compile from source error. Mixer plugin fails.
Log: https://pastebin.com/raw/CdfK0rwt

**Comment by jsyarrow** [comment]
This was addressed in mainline a while back by 2f09666, but I need to get the fix moved across to the UWP tree,

**Comment by JustinBWatson** [comment]
I figured. I adjusted that line and compile is rebuilding now. Thank you so much for all the updates you pushed today. You rock!

**Comment by JustinBWatson** [comment]
Update. Made the change suggested and now massive failure with the Third Party CPPREST SDK. I'm going to just disable this plugin until it will compile with VS 2017. Can't wait to try it out though!
