### ISSUE TITLE
Not compiled Win32

### ISSUE THREAD

**Issue by BelovIgor** [mixer/interactive-unreal-plugin#8]
I tried to compile, but there is a link error
VS2015, UE 4.17.2

**Comment by payzer** [comment]
@BelovIgor I wanted to let you know we have seen the issue. Is this the same issue that we are on an email thread about? (I want to know for tracking so when we resolve that issue, if I can close this one)

**Comment by BelovIgor** [comment]
Hi Gersh! Yes, this is the same issue. Thanks!

**Comment by AechDub** [comment]
I believe this one is resolved.  Is this still an issue?

**Comment by BelovIgor** [comment]
No! Thanks )
